### PR TITLE
[WIP] ES6 + UMD

### PR DESCRIPTION
**Pull request by callumacrae**
This PR will turn justice.js into an ES6 module and use browserify and babelify to transpile that into ES5 using UMD.

Size before: 7178 bytes
Size after: 10608 bytes

### CODE REVIEW

**Comment by okor** [comment]
@callumacrae I just quickly pulled this down and created a fresh build and noticed that the examples/simple.html page doesn't work, 'Justice' returning undefined. Perhaps you could take a look?

**Comment by callumacrae** [comment]
Yep, that's expected at this point. It's working locally now that I've got rid of grunt-include, will tidy up and commit in a bit.

**Comment by callumacrae** [comment]
Okay, that should do it. Unfortunately it's increased the size of the output file by 3.5kb, but I'm not sure there's any way around that without scrapping the module syntax and going back to grunt-include, which I didn't like very much.

**Comment by okor** [comment]
@callumacrae Seems to be very close. I pulled this down and did a fresh build, example page is still broken. So, I think the way we should handle this is to provide two builds. We still need to maintain the plain old javascript file pattern in addition to using any number of other module based build tool/workflows. 

Meaning, we must have a build which exports `Justice` into the parent window object. Not everyone is going to want to use a module. Once the example page is working, I can do a more in depth review and probably merge. Thanks!

**Comment by callumacrae** [comment]
d'oh, I fixed it and forgot to push it. Gimme a sec

**Comment by callumacrae** [comment]
There we go, that will have fixed the example page. It exports to the window object unless it is imported as a module, so it won't break now.

**Comment by callumacrae** [comment]
@okor Hey, have you had any time to look at this?

**Comment by okor** [comment]
@callumacrae Yes but I've been a bit conflicted on how to proceed. After some thinking and advice from @gmac I think that we should create a test suite before we make the transition to ES6. I want the library to be properly stable so we can make changes with confidence. In order to have testable code, we really need to rewrite Justice in an object oriented manor. I feel a bit bad for reneging but really believe we should handle that first. Feels?

**Comment by callumacrae** [comment]
I'd agree that tests would be a good thing, but I don't see how rewriting it in an object oriented manor would help. Functional code can absolutely be tested!

**Comment by callumacrae** [comment]
@okor Any update?

**Comment by okor** [comment]
@callumacrae I really am truly sorry about the absurd delay on this. I simply haven't had the time. But I do feel like creating tests should be a first step. As soon as I see a window of time I'll build out the tests.

I'll see if I can figure out a way to dedicate some time from my day job to get this done. We do use it in house and there are few features we'd like to ad, so that's possible. I have a big project that's still in process. Once that's out of the way I should have time for this.

**Comment by callumacrae** [comment]
Awesome, thank you! Let me know if there's anything I can do to help.

**Pull request closed without merging**
